version: '3'
services:
  provider_portal:
    build: ./provider_portal
    ports: 
      - '443:443'
    volumes:
      - .:/app/provider_portal

  smart_meter:
    build: ./smart_meter
    volumes:
      - .:/app/smart_meter